// <auto-generated />
using System;
using CheckSkillsASP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckSkillsASP.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240303212616_SeedUsers")]
    partial class SeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CheckSkillsASP.Entity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("WasCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            City = "New York",
                            ConcurrencyStamp = "e96c0f78-7d41-4bce-bed4-4b643b91ab3f",
                            Country = "USA",
                            Email = "johndoe@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "Johnny",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "JohnDoe",
                            WasCreated = new DateTime(2024, 3, 3, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            City = "London",
                            ConcurrencyStamp = "0d670bc3-90e2-4d95-9139-fbf7ba55c14a",
                            Country = "UK",
                            Email = "alicesmith@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "AliSmith",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "AliceSmith",
                            WasCreated = new DateTime(2024, 3, 3, 12, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            City = "Madrid",
                            ConcurrencyStamp = "dd78c70f-dbfa-43a6-9e29-f8f39aeafc5a",
                            Country = "Spain",
                            Email = "carlosgomez@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "GomezC",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "CarlosGomez",
                            WasCreated = new DateTime(2024, 3, 3, 12, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            City = "Tokyo",
                            ConcurrencyStamp = "d4dfd894-0030-4962-a081-b977b9a7015c",
                            Country = "Japan",
                            Email = "yukisato@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "YukiSan",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "YukiSato",
                            WasCreated = new DateTime(2024, 3, 3, 12, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            City = "Prague",
                            ConcurrencyStamp = "303e5fb2-c60c-4e8c-b92d-029c09b9786e",
                            Country = "Czech Republic",
                            Email = "elenakovac@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "Lena",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ElenaKovac",
                            WasCreated = new DateTime(2024, 3, 3, 12, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            City = "Cairo",
                            ConcurrencyStamp = "45f764ce-d6ef-4245-9bd1-c39106cbe716",
                            Country = "Egypt",
                            Email = "mohammedali@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "TheGreatest",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "MohammedAli",
                            WasCreated = new DateTime(2024, 3, 3, 12, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            City = "Paris",
                            ConcurrencyStamp = "b2805698-d260-48e4-86e1-267cb17e01d6",
                            Country = "France",
                            Email = "sophiemiller@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "SophieM",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "SophieMiller",
                            WasCreated = new DateTime(2024, 3, 3, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            City = "Mumbai",
                            ConcurrencyStamp = "02c091cd-5d25-44ce-aafe-9c7bfaabfee1",
                            Country = "India",
                            Email = "rajpatel@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "RajP",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "RajPatel",
                            WasCreated = new DateTime(2024, 3, 3, 12, 35, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            City = "Buenos Aires",
                            ConcurrencyStamp = "c792dd6d-c751-4ad2-b0d7-5576cdfbeff8",
                            Country = "Argentina",
                            Email = "luisafernandez@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "LuisaF",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "LuisaFernandez",
                            WasCreated = new DateTime(2024, 3, 3, 12, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            City = "Osaka",
                            ConcurrencyStamp = "51dae046-383b-4a7c-98aa-02c2a468257c",
                            Country = "Japan",
                            Email = "kenjitanaka@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "KTanaka",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "KenjiTanaka",
                            WasCreated = new DateTime(2024, 3, 3, 12, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            City = "Moscow",
                            ConcurrencyStamp = "57a15f76-6e21-4428-a4e0-9d044e766429",
                            Country = "Russia",
                            Email = "anastasiaivanova@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "AnaIvanova",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "AnastasiaIvanova",
                            WasCreated = new DateTime(2024, 3, 3, 12, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            City = "Barcelona",
                            ConcurrencyStamp = "9f7b80cc-fd56-424d-abf2-4c85f6993a0b",
                            Country = "Spain",
                            Email = "antoniolopez@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "TonyLopez",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "AntonioLopez",
                            WasCreated = new DateTime(2024, 3, 3, 12, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            City = "Delhi",
                            ConcurrencyStamp = "6fa54dd2-26a4-435b-8c09-cd531331073a",
                            Country = "India",
                            Email = "priyaverma@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "PriyaV",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "PriyaVerma",
                            WasCreated = new DateTime(2024, 3, 3, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            AccessFailedCount = 0,
                            City = "Buenos Aires",
                            ConcurrencyStamp = "3a2d004f-c67e-4e54-91d3-6a9eda121303",
                            Country = "Argentina",
                            Email = "javierrodriguez@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "JaviRod",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "JavierRodriguez",
                            WasCreated = new DateTime(2024, 3, 3, 13, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            AccessFailedCount = 0,
                            City = "Sydney",
                            ConcurrencyStamp = "701dd64f-ae5f-4a35-8cca-117a797e9d61",
                            Country = "Australia",
                            Email = "emilyjohnson@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "EmJ",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "EmilyJohnson",
                            WasCreated = new DateTime(2024, 3, 3, 13, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            AccessFailedCount = 0,
                            City = "Sofia",
                            ConcurrencyStamp = "c2315a02-4de9-43ca-968b-e44e59a5878c",
                            Country = "Bulgaria",
                            Email = "ivanivanov@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "IvanI",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "IvanIvanov",
                            WasCreated = new DateTime(2024, 3, 3, 13, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            AccessFailedCount = 0,
                            City = "Mexico City",
                            ConcurrencyStamp = "0e7b52bf-272c-42cc-b48d-03a5d849b62a",
                            Country = "Mexico",
                            Email = "sofiamartinez@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "SofiaM",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "SofiaMartinez",
                            WasCreated = new DateTime(2024, 3, 3, 13, 20, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("CheckSkillsASP.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("CheckSkillsASP.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheckSkillsASP.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("CheckSkillsASP.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
