// <auto-generated />
using System;
using CheckSkillsASP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckSkillsASP.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240331180808_TestMigration")]
    partial class TestMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CheckSkillsASP.Entity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("WasCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            City = "New York",
                            ConcurrencyStamp = "710cbe74-d6de-4ec8-9ce7-8390ac132e92",
                            Country = "USA",
                            Email = "johndoe@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "Johnny",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "JohnDoe",
                            WasCreated = new DateTime(2024, 3, 3, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            City = "London",
                            ConcurrencyStamp = "bb047f56-792c-4937-8bc7-9e483a054248",
                            Country = "UK",
                            Email = "alicesmith@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "AliSmith",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "AliceSmith",
                            WasCreated = new DateTime(2024, 3, 3, 12, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            City = "Madrid",
                            ConcurrencyStamp = "b3f969c7-9b53-464a-8a74-f9e57eca1cf6",
                            Country = "Spain",
                            Email = "carlosgomez@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "GomezC",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "CarlosGomez",
                            WasCreated = new DateTime(2024, 3, 3, 12, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            City = "Tokyo",
                            ConcurrencyStamp = "0c3219f0-2800-4e22-b459-5e6d3d156443",
                            Country = "Japan",
                            Email = "yukisato@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "YukiSan",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "YukiSato",
                            WasCreated = new DateTime(2024, 3, 3, 12, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            City = "Prague",
                            ConcurrencyStamp = "2149bd0f-a95a-49ec-90e7-308bdebd218b",
                            Country = "Czech Republic",
                            Email = "elenakovac@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "Lena",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "ElenaKovac",
                            WasCreated = new DateTime(2024, 3, 3, 12, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            City = "Cairo",
                            ConcurrencyStamp = "45306598-36c3-4681-abfa-7551c412e06e",
                            Country = "Egypt",
                            Email = "mohammedali@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "TheGreatest",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "MohammedAli",
                            WasCreated = new DateTime(2024, 3, 3, 12, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            City = "Paris",
                            ConcurrencyStamp = "ffa3eb30-d49f-4fe8-9743-709f0cd22c12",
                            Country = "France",
                            Email = "sophiemiller@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "SophieM",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "SophieMiller",
                            WasCreated = new DateTime(2024, 3, 3, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            City = "Mumbai",
                            ConcurrencyStamp = "590b8ac3-e49f-44c0-812e-d60104c9aae3",
                            Country = "India",
                            Email = "rajpatel@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "RajP",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "RajPatel",
                            WasCreated = new DateTime(2024, 3, 3, 12, 35, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            City = "Buenos Aires",
                            ConcurrencyStamp = "a03fd453-71b8-4b0e-a14a-2e7c03035c06",
                            Country = "Argentina",
                            Email = "luisafernandez@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "LuisaF",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "LuisaFernandez",
                            WasCreated = new DateTime(2024, 3, 3, 12, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            City = "Osaka",
                            ConcurrencyStamp = "41ac1b26-e07c-44e0-b786-b46ee7c1e338",
                            Country = "Japan",
                            Email = "kenjitanaka@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "KTanaka",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "KenjiTanaka",
                            WasCreated = new DateTime(2024, 3, 3, 12, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            City = "Moscow",
                            ConcurrencyStamp = "d9cfa24f-8b0e-4a54-b892-1e2102c6f170",
                            Country = "Russia",
                            Email = "anastasiaivanova@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "AnaIvanova",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "AnastasiaIvanova",
                            WasCreated = new DateTime(2024, 3, 3, 12, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            City = "Barcelona",
                            ConcurrencyStamp = "dd6c1cfa-5492-46ed-868e-444c8844239b",
                            Country = "Spain",
                            Email = "antoniolopez@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "TonyLopez",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "AntonioLopez",
                            WasCreated = new DateTime(2024, 3, 3, 12, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            City = "Delhi",
                            ConcurrencyStamp = "cdae6174-a69b-4da4-8d45-5dd38ab39ed1",
                            Country = "India",
                            Email = "priyaverma@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "PriyaV",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "PriyaVerma",
                            WasCreated = new DateTime(2024, 3, 3, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            AccessFailedCount = 0,
                            City = "Buenos Aires",
                            ConcurrencyStamp = "2b41b709-b38e-405e-b5d1-ae0f3c6d80a1",
                            Country = "Argentina",
                            Email = "javierrodriguez@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "JaviRod",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "JavierRodriguez",
                            WasCreated = new DateTime(2024, 3, 3, 13, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            AccessFailedCount = 0,
                            City = "Sydney",
                            ConcurrencyStamp = "85edd209-ede6-4e02-b27b-86be958f1f90",
                            Country = "Australia",
                            Email = "emilyjohnson@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "EmJ",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "EmilyJohnson",
                            WasCreated = new DateTime(2024, 3, 3, 13, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            AccessFailedCount = 0,
                            City = "Sofia",
                            ConcurrencyStamp = "02b578a2-4166-455a-8830-97e9643d8113",
                            Country = "Bulgaria",
                            Email = "ivanivanov@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "IvanI",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "IvanIvanov",
                            WasCreated = new DateTime(2024, 3, 3, 13, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            AccessFailedCount = 0,
                            City = "Mexico City",
                            ConcurrencyStamp = "4479f7c2-4e77-4ba2-a173-19ed330aa3d9",
                            Country = "Mexico",
                            Email = "sofiamartinez@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NickName = "SofiaM",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "SofiaMartinez",
                            WasCreated = new DateTime(2024, 3, 3, 13, 20, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("CheckSkillsASP.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("CheckSkillsASP.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheckSkillsASP.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("CheckSkillsASP.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
